### ISSUE TITLE
Request: Dynamic-symmetry

### ISSUE THREAD

**Issue by Dziban-dev** [Grum999/CompositionHelper#4]
So I tried your plugin and LOVED IT, very useful I just wanted to point out that for creating dynamic symmetry compositions it would be great to add diagonals that intersect the other corners of the rule of thirds intersection, see the lines I highlighted in yellow below: (ignore the red marks) 

<a href="https://ibb.co/2Fkr4Px"><img src="https://i.ibb.co/2Fkr4Px/dynamic-symetry.png" alt="dynamic-symetry" border="0"></a>

I think that is the only thing missing for this great plugin.

**Comment by Grum999** [comment]
Hi!

Thanks for feedback
I've added this request in my TODO list 🙂

Additional information:
https://photographycourse.net/dynamic-symmetry

Grum999

**Comment by Grum999** [comment]
Hi @Dziban-dev 

I've started implementation, but I have a doubt 

Looking for different place to be sure about terminology, and I saw different explanation about "Dynamic Symmetry"

Looking this image built from dev version of _CompositionHelper_ plugin:
<img width="500" alt="image" src="https://github.com/Grum999/CompositionHelper/assets/63422799/87a260ff-ba97-4a98-9270-4d189d7633a2">

- In blue, golden sections 
- In red, rule of thirds

You'll have "dynamic symmetry":
- in green, based on rules of thirds 
- in magenta, based on golden sections

Also, I found other meaning for _Dynamic Symmetry_ where instead of having lines passing through cross section, it's included in rectangles:
- in yellow, based on rules of thirds 
- in white, based on golden sections

I can let all of these helpers (they're already implemented on my side) in plugin, but I want to be sure to properly name them

Do you have an idea about names?
Currently what I've defined:
<img width="287" alt="image" src="https://github.com/Grum999/CompositionHelper/assets/63422799/3655d00b-da25-4e30-a1a7-c9fdd0494095">
But as I can't find a site where naming and rules are defined with the same definitions... 

Thanks 


Grum999

**Comment by Grum999** [comment]
Waiting few days before considering it as implemented 
Release 1.2.0 will be published in the same time

**Comment by Grum999** [comment]
No feedback, considering that names doesn't matter (at least, names I've defined are ok)
